### ISSUE TITLE
Don't store requester's public key in QuestionNote

### ISSUE THREAD

**Issue by spalladino** [defi-wonderland/aztec-private-oracle#2]
The requester's public key should be broadcasted to the network when they deploy their account contract, and automatically added to everyone's PXE. This allows you to call `get_public_key` for the `requester_address` from any PXE.

https://github.com/defi-wonderland/aztec-private-oracle/blob/afe8cb4e3bc34219f925859790be56c79fb0188c/src/types/question_note.nr#L40

**Comment by simon-something** [comment]
Oh great, didn't see the PR in the docs about this - good to know

**Comment by 0xShaito** [comment]
https://github.com/defi-wonderland/aztec-private-oracle/commit/56b0cfd31bdb8ece4287816657118b8e6583940f
