### ISSUE TITLE
Recipient pubkey in QuestionNote nullifier

### ISSUE THREAD

**Issue by spalladino** [defi-wonderland/aztec-private-oracle#3]
I'm curious why you are adding the recipient's pubkey to the nullifier inputs, given it's already part of the computed note hash a few lines above (assuming it doesn't get removed as per #2).

https://github.com/defi-wonderland/aztec-private-oracle/blob/afe8cb4e3bc34219f925859790be56c79fb0188c/src/types/question_note.nr#L79-L80

**Comment by 0xShaito** [comment]
Removed: https://github.com/defi-wonderland/aztec-private-oracle/commit/56b0cfd31bdb8ece4287816657118b8e6583940f
