### ISSUE TITLE
Can't trust oracle for checking non-existance of notes

### ISSUE THREAD

**Issue by spalladino** [defi-wonderland/aztec-private-oracle#4]
A malicious user could tweak their oracle so it doesn't return the note in this request, effectively creating duplicate requests. Nevertheless, it'd seem like the user would just be hurting themselves by doing so, right? In that case, it's fine to leave it as is.

https://github.com/defi-wonderland/aztec-private-oracle/blob/afe8cb4e3bc34219f925859790be56c79fb0188c/src/main.nr#L101-L104

**Comment by skeletor-spaceman** [comment]
yes. the user would just pay one "extra" time for the same request. (this is a check to "save" honest users of paying for the same question multiple times)
