### ISSUE TITLE
Remove assertions for note getter options once 0.8.x is out

### ISSUE THREAD

**Issue by spalladino** [defi-wonderland/aztec-private-oracle#5]
These are now automatically checked by `get_notes`, which checks that the results returned by the oracle match the selection criteria.

https://github.com/defi-wonderland/aztec-private-oracle/blob/afe8cb4e3bc34219f925859790be56c79fb0188c/src/main.nr#L149-L150

**Comment by skeletor-spaceman** [comment]
oh, this is nice, definitely a good improvement on overall security :)

**Comment by 0xShaito** [comment]
https://github.com/defi-wonderland/aztec-private-oracle/commit/56b0cfd31bdb8ece4287816657118b8e6583940f
